2025-05-07 20:02:55,587 - INFO - NVTabular version: 23.08.00
2025-05-07 20:02:55,587 - INFO - cuDF version: 23.04.01
2025-05-07 20:02:55,587 - INFO - Pandas version: 1.5.3
2025-05-07 20:02:55,591 - INFO - Creating preload: dask_cuda.initialize
2025-05-07 20:02:55,591 - INFO - Import preload module: dask_cuda.initialize
2025-05-07 20:02:55,613 - INFO - Run preload setup: dask_cuda.initialize
2025-05-07 20:02:55,807 - INFO -       Start worker at:      tcp://127.0.0.1:46799
2025-05-07 20:02:55,807 - INFO -          Listening to:      tcp://127.0.0.1:46799
2025-05-07 20:02:55,807 - INFO -           Worker name:                          0
2025-05-07 20:02:55,807 - INFO -          dashboard at:            127.0.0.1:35929
2025-05-07 20:02:55,807 - INFO - Waiting to connect to:      tcp://127.0.0.1:39405
2025-05-07 20:02:55,807 - INFO - -------------------------------------------------
2025-05-07 20:02:55,807 - INFO -               Threads:                          1
2025-05-07 20:02:55,807 - INFO -                Memory:                 251.74 GiB
2025-05-07 20:02:55,807 - INFO -       Local Directory: /tmp/dask-worker-space/worker-et8efec7
2025-05-07 20:02:55,807 - INFO - Starting Worker plugin RMMSetup-5580abe9-9b28-4c4b-83e2-deb300115809
2025-05-07 20:02:56,344 - INFO - Starting Worker plugin CPUAffinity-eece93ae-2418-4e22-b9ad-4f1ad337eb80
2025-05-07 20:02:56,345 - INFO - Starting Worker plugin PreImport-e02d8ac8-2528-4aeb-9be8-0f57b4b59fb8
2025-05-07 20:02:56,345 - INFO - -------------------------------------------------
2025-05-07 20:02:56,391 - INFO -         Registered to:      tcp://127.0.0.1:39405
2025-05-07 20:02:56,391 - INFO - -------------------------------------------------
2025-05-07 20:02:56,392 - INFO - Starting established connection to tcp://127.0.0.1:39405
2025-05-07 20:03:00,079 - INFO - Run out-of-band function 'clean_worker_cache'
2025-05-07 20:03:01,629 - ERROR - Failed to transform operator <merlin.dag.ops.udf.UDF object at 0x7f49f1871840>
Traceback (most recent call last):
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/base.py", line 701, in cast
    impl = self._casts.find((fromty, toty))
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/base.py", line 44, in find
    out = self._find(sig)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/base.py", line 53, in _find
    raise errors.NumbaNotImplementedError(f'{self}, {sig}')
numba.core.errors.NumbaNotImplementedError: [1m<numba.core.base.OverloadSelector object at 0x7f4b1578c850>, (string_view, int64)[0m

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/cudf/core/indexed_frame.py", line 2136, in _apply
    kernel, retty = _compile_or_get(
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/nvtx/nvtx.py", line 122, in inner
    result = func(*args, **kwargs)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/cudf/core/udf/utils.py", line 298, in _compile_or_get
    kernel, scalar_return_type = kernel_getter(frame, func, args)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/cudf/core/udf/scalar_function.py", line 55, in _get_scalar_kernel
    scalar_return_type = _get_udf_return_type(sr_type, func, args)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/nvtx/nvtx.py", line 122, in inner
    result = func(*args, **kwargs)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/cudf/core/udf/utils.py", line 144, in _get_udf_return_type
    ptx, output_type = cudautils.compile_udf(func, compile_sig)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/cudf/utils/cudautils.py", line 250, in compile_udf
    ptx_code, return_type = cuda.compile_ptx_for_current_device(
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/cuda/compiler.py", line 293, in compile_ptx_for_current_device
    return compile_ptx(pyfunc, args, debug=debug, lineinfo=lineinfo,
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/cuda/compiler.py", line 269, in compile_ptx
    cres = compile_cuda(pyfunc, None, args, debug=debug, lineinfo=lineinfo,
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/cuda/compiler.py", line 212, in compile_cuda
    cres = compiler.compile_extra(typingctx=typingctx,
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/compiler.py", line 716, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/compiler.py", line 452, in compile_extra
    return self._compile_bytecode()
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/compiler.py", line 520, in _compile_bytecode
    return self._compile_core()
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/compiler.py", line 499, in _compile_core
    raise e
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/compiler.py", line 486, in _compile_core
    pm.run(self.state)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/typed_passes.py", line 394, in run_pass
    lower.lower()
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/lowering.py", line 168, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/lowering.py", line 222, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/lowering.py", line 251, in lower_function_body
    self.lower_block(block)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/lowering.py", line 265, in lower_block
    self.lower_inst(inst)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/lowering.py", line 439, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/lowering.py", line 626, in lower_assign
    return self.lower_expr(ty, value)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/lowering.py", line 1162, in lower_expr
    res = self.lower_call(resty, expr)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/lowering.py", line 891, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/lowering.py", line 1133, in _lower_call_normal
    res = impl(self.builder, argvals, self.loc)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/base.py", line 1190, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/base.py", line 1220, in wrapper
    return fn(*args, **kwargs)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/cudf/core/udf/masked_lowering.py", line 325, in masked_scalar_cast_impl
    casted = context.cast(
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/numba/core/base.py", line 704, in cast
    raise errors.NumbaNotImplementedError(
numba.core.errors.NumbaNotImplementedError: Failed in cuda mode pipeline (step: native lowering)
[1m[1mCannot cast string_view to int64: %".24" = load {i8*, i32, i32}, {i8*, i32, i32}* %".23"[0m
[0m[1mDuring: lowering "$8call_function.3 = call $2load_global.0(x, $const6.2, func=$2load_global.0, args=[Var(x, nvtabular_gpu_1TB_8k_no_vocab_dask.py:157), Var($const6.2, nvtabular_gpu_1TB_8k_no_vocab_dask.py:157)], kws=(), vararg=None, varkwarg=None, target=None)" at /home/yuzhuyu/u55c/rec_preprocessing/nvtabular_gpu_1TB_8k_no_vocab_dask.py (157)[0m

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/merlin/dag/executors.py", line 237, in _run_node_transform
    transformed_data = node.op.transform(selection, input_data)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/merlin/dag/ops/udf.py", line 78, in transform
    new_df[col] = self.f(transformable[col])
  File "/home/yuzhuyu/u55c/rec_preprocessing/nvtabular_gpu_1TB_8k_no_vocab_dask.py", line 157, in <lambda>
    >> LambdaOp(lambda col: col.fillna("0").str.lower().apply(lambda x: int(x, 16) % vocab_size))
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/nvtx/nvtx.py", line 122, in inner
    result = func(*args, **kwargs)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/cudf/core/series.py", line 2460, in apply
    result = self._apply(func, _get_scalar_kernel, *args, **kwargs)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/nvtx/nvtx.py", line 122, in inner
    result = func(*args, **kwargs)
  File "/home/yuzhuyu/miniconda3/envs/nvtabular_23_08/lib/python3.10/site-packages/cudf/core/indexed_frame.py", line 2140, in _apply
    raise ValueError(
ValueError: user defined function compilation failed.
2025-05-07 20:03:01,655 - WARNING - Compute Failed
Key:       ('transform-1ffc5bedc656f7596c74b7f1f8cd0249', 0)
Function:  subgraph_callable-2771ed87-92a5-42b4-9a55-98413865
args:      ({'piece': ('/mnt/scratch/yuzhuyu/parquet/criteo_1TB/criteo_1TB_part_0000.parquet', [0, 1, 2, 3], [])})
kwargs:    {}
Exception: "ValueError('user defined function compilation failed.')"

2025-05-07 20:03:01,763 - INFO - Stopping worker at tcp://127.0.0.1:46799. Reason: nanny-close
2025-05-07 20:03:01,764 - INFO - Connection to tcp://127.0.0.1:39405 has been closed.
